### ISSUE TITLE
Error: graphiql:45 Uncaught ReferenceError: GraphiQL is not defined(…)

### ISSUE THREAD

**Issue by RivkaRoth** [calebmer/postgraphql#254] opened 2016-11-27 08:14 UTC
I did the following steps:
1. Installed node v 6.9.1 :
node -v
v6.9.1
2. Installed postgraphql: npm install -g postgraphql
3. Run postgraphql: postgraphql -c postgres://postgres@localhost:5432/myDb

It seems postgraphql is running:
PostGraphQL server listening on port 5000 �

  ‣ Connected to Postgres instance postgres://localhost:5432/myDb
  ‣ Introspected Postgres schema(s) public
  ‣ GraphQL endpoint served at http://localhost:5000/graphql
  ‣ GraphiQL endpoint served at http://localhost:5000/graphiql

* * *

But when I trying connect to GraphiQL at http://localhost:5000/graphiql
I get the following error:
graphiql:45 Uncaught ReferenceError: GraphiQL is not defined(…)(anonymous function) @ graphiql:45

Thanks!

**Comment by RivkaRoth** [comment] 2016-11-27 08:24
I'm working with windows 10.

**Comment by benjie** [comment] 2016-11-27 15:13
Duplicate of #249; are you outside the US, by any chance?

**Closed by benjie** 2016-11-27 15:13 UTC

**Comment by juliusdejon** [comment] 2019-02-13 09:24
just Cntrl f5 due to caching of browser
