### ISSUE TITLE
No exception/warning if port in use

### ISSUE THREAD

**Issue by cmpis** [calebmer/postgraphql#2] opened 2016-04-27 18:44 UTC
Just says it's listening, but in my case something was already listening on that port and it didn't say anything.

**Comment by calebmer** [comment] 2016-04-27 22:59
I couldn't reproduce this 😐

I've started a [Gitter room](https://gitter.im/calebmer/postgraphql) if you wanted to talk about your experiences with PostGraphQL and we could use it to debug this.

**Comment by calebmer** [comment] 2016-04-29 10:26
Closing this as I can't reproduce.

**Closed by calebmer** 2016-04-29 10:26 UTC
