### ISSUE TITLE
v2: Computed columns, only show when stable?

### ISSUE THREAD

**Issue by tim-field** [calebmer/postgraphql#161] opened 2016-10-16 09:26 UTC
Something I noticed, not sure if this is a bug, or something that just needs to be documented. 

The following **will not** add a whatsItMean property to my Project type

```
create function project_whats_it_mean(project project) returns integer as $$
  select 42
$$ language sql
set search_path from current;
```

But this will, only difference being the function type of **stable** added. 

```
create function project_whats_it_mean(project project) returns integer as $$
  select 42
$$ language sql stable
set search_path from current;
```

**Comment by calebmer** [comment] 2016-10-16 12:13
This is intended behavior 👍

In order to be considered a query, a function must be marked as stable. Since computed fields are queries, the computed field procedure must also be stable.

I'll leave this open until I document changes.

**Comment by calebmer** [comment] 2016-10-16 14:37
Fixed in https://github.com/calebmer/postgraphql/commit/e9c12df25663ca8312e8b7bc4b41fc7950f93a24 :+1:

**Closed by calebmer** 2016-10-16 14:37 UTC
