### ISSUE TITLE
How to update column value with mutation to NULL

### ISSUE THREAD

**Issue by langpavel** [calebmer/postgraphql#108] opened 2016-09-07 01:06 UTC
Hi @calebmer. I'm challenging problem. How I can set value to `NULL`?

![image](https://cloud.githubusercontent.com/assets/142462/18296199/0f8f8072-74a8-11e6-8ace-89af7314f452.png)

**Comment by langpavel** [comment] 2016-09-07 01:37
One possible solution is to add boolean fields into `Input` shape for each nullable column,
like `newImageFeatured` for setting value
and `imageFeaturedSetNull` or `nullImageFeatured` for database `NULL`.

**Comment by calebmer** [comment] 2016-09-07 11:18
This definitely looks like a bug. I'll investigate 👍

**Comment by langpavel** [comment] 2016-09-08 19:55
@calebmer Can you point out some relevant pieces of code for me? I can prepare PR for this, but I feel there will be more discussion about this... So, any ideas? I really want this feature :smiling_imp:

**Comment by calebmer** [comment] 2016-09-08 21:49
For sure :blush:

[This statement](https://github.com/calebmer/postgraphql/blob/02b1058795a70d3de5367da2b5ef5742499a7c20/src/graphql/mutation/createUpdateMutationField.js#L107-L115) will be what you want to look at. Also, [here where `setClauses`](https://github.com/calebmer/postgraphql/blob/02b1058795a70d3de5367da2b5ef5742499a7c20/src/graphql/mutation/createUpdateMutationField.js#L94-L99) gets defined.

Also a quick crash-course on [`SQLBuilder`](https://github.com/calebmer/postgraphql/blob/02b1058795a70d3de5367da2b5ef5742499a7c20/src/SQLBuilder.js) (it was a quick and dirty solution, there’s a much [cleaner SQL builder in the `next`](https://github.com/calebmer/postgraphql/blob/8b3aa119e24646408b10a3863b5bb9a12b5aa549/src/postgres/catalog/conditionToSQL.ts) branch :wink:). Counting up (think `$1`, `$2`, `$3`, etc.) like in normal prepared statements is hard to keep track of and very difficult to compose. So `SQLBuilder` allows you to just use `$` and pass the array of ordered values like you normally would. Then `SQLBuilder` will compose those `$` to have the correct index.

The bug may be [here](https://github.com/calebmer/postgraphql/blob/02b1058795a70d3de5367da2b5ef5742499a7c20/src/graphql/mutation/createUpdateMutationField.js#L96) or it may be as easy a fix as changing [this](https://github.com/calebmer/postgraphql/blob/02b1058795a70d3de5367da2b5ef5742499a7c20/src/graphql/mutation/createUpdateMutationField.js#L97-L98) to:

```js
if (value === null) {
  setClauses.push(`"${column.name}" = null`)
}
else {
  setClauses.push(`"${column.name}" = $`)
  setValues.push(value)
}
```

([`pg`](http://npmjs.com/pg) may not like `null`s :blush:)

Let me know how it goes :+1: :tada:

**Comment by langpavel** [comment] 2016-09-10 21:00
Thanks! Will look. Btw do you like way I'm using template strings in my pg-async library?

**Comment by calebmer** [comment] 2016-09-10 23:57
It depends, how much do you support? :wink: I didn’t see any documentation when I looked quickly.

I really don’t like `SQLBuilder` (it was the best I could do at the time…), so I’m going to talk more about the PostGraphQL 2 SQL builder.

Some requirements for a SQL builder used by PostGraphQL is:

- Supports identifier variables. So something like `"forum_example"."person"."id"` can be added as so ``sql.query`${sql.identifier('forum_example', 'person', 'id')} = 1` ``.
- Allows for both eager and lazy values. Therefore you could do `column = ${sql.value(1)}` or `column = ${sql.placeholder('num')}` and then inject a value for `num` later. In both cases though we still need to use PostgreSQL placeholders with auto-incrementing “names” (`$1`, `$2`, `$3`, etc).
- Must be type safe. This is more a design constraint of PostGraphQL 2 though.

The implementation I landed on is also pretty fast. At the end of the days it’s just some string concatenation. Under the hood everything is an object though, it takes the strings and turns it into an array, so a query like:

```js
sql.query`where ${sql.identifier('a', 'b', 'c')} = ${sql.value(value)}`
```

Turns into:

```js
[{ type: 'RAW', text: 'where ' }, { type: 'IDENTIFIER', names: ['a', 'b', 'c'] }, { type: 'RAW', text: ' = ' }, { type: 'VALUE', value: value }]
```

I really like the API/implementation I ended up with, but I’m always open to new ideas :blush:

**Comment by calebmer** [comment] 2016-09-21 15:54
After some more research, I remembered that there is no idea of “null” for inputs in GraphQL. See this issue https://github.com/graphql/graphql-js/issues/133 and this RFC pull request https://github.com/facebook/graphql/pull/83

For now if you want to continue with your proposal (`imageFeaturedSetNull` etc) go for it, just know it will probably be deprecated when we get support for the null literal in GraphQL :+1:

Another option is we could add a `removedColumns` array, but I like the idea of `imageFeaturedSetNull` better more personally.

**Comment by langpavel** [comment] 2016-10-28 03:02
Hi. I just finished new PR https://github.com/graphql/graphql-js/pull/544 extending GraphQL with `null` literal in GraphQL language itself so RFC will be fulfilled soon I hope :-)

But it looks that null values are supported already in graphql-js@master.

What is state of this issue? Are explicit nulls still unhandled?

**Comment by calebmer** [comment] 2016-10-28 12:49
I’ve been watching the progress, great job :blush:

I’ll have to check and see if `null` values are supported, but I’ll definitely make sure everything works as expected when https://github.com/graphql/graphql-js/pull/544 lands :+1:

**Comment by benjie** [comment] 2016-11-01 05:47
Looks like https://github.com/graphql/graphql-js/pull/544 just got merged!

**Comment by calebmer** [comment] 2016-11-01 18:28
:tada: now just waiting for it to get released in `0.8.0` then I’ll test to make sure everything works as expected.

Also see https://github.com/calebmer/postgraphql/issues/202

**Comment by ferdinandsalis** [comment] 2016-11-25 13:26
@calebmer what is the status of this?

**Comment by calebmer** [comment] 2016-11-27 14:48
@ferdinandsalis I can confirm this works, just make sure you have a version of GraphQL above `0.8.0` :+1:

Submit a PR to add tests and prevent regression, once that gets merged we can close this issue: https://github.com/calebmer/postgraphql/pull/255

**Closed** 2016-11-27 15:11 UTC
Labels: bug
